Vagrant.configure(2) do |config|

  config.vm.define "ac" do |ac|
    ac.vm.box = "debian/jessie64" # www.vagrantcloud.com
    ac.vm.hostname = "ac"
    ac.vm.network "private_network", ip: "192.168.33.10"
  end
  
  config.vm.define "web" do |web|
    web.vm.box = "centos/7"
    web.vm.hostname = "web"
    web.vm.network "private_network", ip: "192.168.33.20"
    web.vm.network "forwarded_port", guest: 80, host: 8080
  end

  config.vm.define "db" do |db|
    db.vm.box = "centos/7"
    db.vm.hostname = "db"
    db.vm.network "private_network", ip: "192.168.33.30"
  end

end
